### ISSUE TITLE
Adding metrics

### ISSUE THREAD

**Issue by lferran** [guillotinaweb/guillotina_amqp#23]
It would be nice to add custom metrics that can later be exported to prometheus.
Any ideas on how could this be done?

I guess first step would be to make `guillotina_prometheus` as a requirement of this plugin?

Then add a custom middleware?

**Comment by vangheem** [comment]
I think you conditionally check if `prometheus_client` is installed.

Then, just make sure to log whatever you need: https://github.com/guillotinaweb/guillotina_prometheus/blob/master/guillotina_prometheus/middleware.py#L22

Don't make it a requirement though!

**Comment by lferran** [comment]
Metrics to add:
 - number of currently running jobs (gauge)
 - job execution time (histogram)
 - more?

Labels to think about: 
 - function name
 - worker id
 - more?

**Comment by vangheem** [comment]
that's a really good start! Thanks for working on this!
