### ISSUE TITLE
Newer versions not published to pipy

### ISSUE THREAD

**Issue by lferran** [guillotinaweb/guillotina_amqp#9]
Even though the tag an the release are there for version `2.0.0`, it seems that the package was never uploaded to pipy

```
>> venv/bin/pip install guillotina_amqp==2.0.0                                                                                                    
Collecting guillotina_amqp==2.0.0
  Could not find a version that satisfies the requirement guillotina_amqp==2.0.0 (from versions: 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8)
No matching distribution found for guillotina_amqp==2.0.0
```

**Comment by vangheem** [comment]
I'm not sure I made an actual release. Just making the tag doesn't automatically release.

I'd like to get the 2 issues merged before we make a release I think.

Also, we'll probably need to bump to 2.0.1 since a tag is already pushed out.
